### ISSUE TITLE
Public and Private IPs cycle every new deployment

### ISSUE THREAD

**Issue by berv63** [7Factor/terraform-aws-networking#17]
The issue:
    Each time a TF change is made to either this module or the client calling the module it tends to trigger a destroy/recreate of the bastion host and the new host usually gets a new public and private IP address. We would like this module to implement elastic IPs so that the IPs don't cycle each time as well as a route53 record that we can pass in the record name to redirect to the EIP.  

    https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html

**Comment by berv63** [comment]
While trying to implement the above EIP and Route53 in this module we ran into the following issues with trying to add an EIP `for_each` bastion. 
![image](https://github.com/7Factor/terraform-aws-networking/assets/4182782/767a8a89-076f-43b2-9e07-7d6c6c4bd0de)

The possible solutions for this issue are not ideal and it made us rethink the original code's premise that anyone would have more than one bastion host in a single environment. Because there are no load balancers in front of them it seems unlikely that this would be the case. 

Options:
1. Have the client decide which bastions should have EIPs (putting the onus on the client and not this module)
2. Force this module to apply changes twice. Once to apply the bastions, and again to apply the EIP/Route53
3. Remove the idea that there could be more than 1 bastion, and put the EIP and Route53 on the single host

**Comment by dumptruckman** [comment]
Per jduv, multiple bastion hosts would only be useful if there was a LB in front of them. As such, what if we solve this by providing an EIP directly to the bastion host if only 1 bastion host is specified. If multiple are specified, the module adds an LB and the EIP would be attached to that. This would potentially mean we can solve this in a minor version change instead of a major version change that would be required for removing the ability to create multiple bastion hosts with the module.

**Comment by berv63** [comment]
Great idea! Thanks for talking through this, that way clients that want auto scaling also have a way to hit both bastions with the same address and the ones that don't still get the benefit of an EIP.
